Repository gaurangkeluskar22/competitive-programming, pull requests merged in 2022-10, with the labels that each got.

#13 Create Add Two Integers code in python
  Add Two Integers code in python
Labels: enhancement

#20 Added Number of Provinces.cpp
  Leetcode/547. Number of Provinces.cpp
Labels: good first issue

#19 Create Swap Nodes In Pairs
  Leetcode/Swap Nodes In Pairs
Labels: good first issue

#18 Create Remove Nth from End of List
  Leetcode/Remove Nth from End of List
Labels: good first issue

#44 Add 1749A Codeforces
  CodeForces/1749A.cpp
Labels: Hacktoberfest

#45 Add Codeforces 1749B
  CodeForces/1749B.cpp
Labels: Hacktoberfest

#47 Adding Password 126-B
  Password.cpp
Labels: Hacktoberfest

#46 Add Codeforces 1742B
  CodeForces/1742B.cpp
Labels: Hacktoberfest

#49 Adding Optimized Bellman-Ford
  Bellman-Ford Optimized.cpp
Labels: Hacktoberfest
